# Generated by Django 5.0.2 on 2024-02-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('re_password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('batch', models.IntegerField()),
            ],
        ),
    ]
