# Generated by Django 5.0.2 on 2024-02-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(max_length=5)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('clas', models.IntegerField(max_length=5)),
                ('result', models.FloatField(max_length=5)),
            ],
        ),
    ]
